### ISSUE TITLE
Several [theorem] counters instead of one

### ISSUE THREAD

**Issue by Islam0mar** [DrWaleedAYousef/My-Stuff-To-Share#3]
Why are you using the same counter for [lemma, exercise, ...](https://github.com/DrWaleedAYousef/My-Stuff-To-Share/blob/master/LaTeX/LaTeX-Lecture-Template/Ver1-DigitalDesign/LectureNotesCS221.tex#L87)?

**Comment by DrWaleedAYousef** [comment]
This is  a style or writing; it is much easier for the reader to go back and forth among the text.

**Comment by Islam0mar** [comment]
I don't mean to criticize your style. If you don't mind to let me know more about your perspective. For example, I find it confusing to read `Lemma 33` while it is the third Lemma.

**Comment by DrWaleedAYousef** [comment]
You are welcome. First, it is one of the styles in mathematical
writing. The idea is that, lemma, corollary, proposition, claim,
theorem, etc. are all statements to be proven. Then, there is nothing
special about each. So, simply just one running counter.

**Comment by Islam0mar** [comment]
Thanks.
